name: TestMySite
favicon: null
layout_spectrum: 0.08699684264138341
typography_spectrum: 0.6201779283583164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5621675816364586
  lightness: 0.9930605222471058
  saturation: 0.9768944794777781
  rhythmicContrast: 0.4725056025199592
purpose: []
